Update bip39 in bdk
I was having issues with unicode normalization when building this crate with egui

```
cargo run
    Updating git repository `https://github.com/bitcoindevkit/bdk`
    Updating crates.io index
error: failed to select a version for `unicode-normalization`.
    ... required by package `bip39 v1.0.1`
    ... which satisfies dependency `bip39 = "^1.0.1"` of package `bdk v1.0.0-alpha.2 (https://github.com/bitcoindevkit/bdk?tag=v1.0.0-alpha.2#2e4bc3c5)`
    ... which satisfies git dependency `bdk` of package `aw_brig v0.1.0 (/Users/matthiasdebernardini/Projects/myproject)`
versions that meet the requirements `=0.1.9` are: 0.1.9

all possible versions conflict with previously selected packages.

  previously selected package `unicode-normalization v0.1.22`
    ... which satisfies dependency `unicode-normalization = "^0.1.17"` (locked to 0.1.22) of package `idna v0.3.0`
    ... which satisfies dependency `idna = "^0.3.0"` (locked to 0.3.0) of package `url v2.3.1`
    ... which satisfies dependency `url = "^2"` (locked to 2.3.1) of package `webbrowser v0.8.10`
    ... which satisfies dependency `webbrowser = "^0.8.3"` (locked to 0.8.10) of package `egui-winit v0.23.0`
    ... which satisfies dependency `egui-winit = "^0.23.0"` (locked to 0.23.0) of package `eframe v0.23.0`
    ... which satisfies dependency `eframe = "^0.23.0"` (locked to 0.23.0) of package `aw_brig v0.1.0 (/Users/matthiasdebernardini/Projects/myproject)`

failed to select a version for `unicode-normalization` which could resolve this conflict
```